update sc types page
massalabs/massa-docs pull request #84
Opened 2023-01-11 15:15 UTC by peterjah

2023-01-17 10:29 UTC, Thykof requested changes

2023-01-17 10:29 UTC, Thykof commented on web3-dev/types.rst
> +    import { Address, call } from '@massalabs/massa-as-sdk';
```suggestion
    import { Address, call } from '@massalabs/massa-as-sdk';
    import { Args } from '@massalabs/as-types';
```

2023-01-17 15:53 UTC, Thykof approved these changes

2023-01-17 16:59 UTC, gregLibert requested changes
:mag: typos.

2023-01-17 16:59 UTC, gregLibert commented on web3-dev/types.rst
> +Massa AS-types package (`@massalabs/as-types`) contains assemblyscript object designed to write smart contracts.
```suggestion
Massa AS-types package (`@massalabs/as-types`) contains assemblyscript objects designed to facilitate the writing of smart contracts.
```

2023-01-17 16:59 UTC, gregLibert commented on web3-dev/types.rst
> +More info at `Currency documentation <https://as-types.docs.massa.net/classes/Currency.html>`_.
```suggestion
More info in the `Currency documentation <https://as-types.docs.massa.net/classes/Currency.html>`_.
```

2023-01-17 16:59 UTC, gregLibert commented on web3-dev/types.rst
> +More info at `Amount documentation <https://as-types.docs.massa.net/classes/Amount.html>`_.
```suggestion
More info in the `Amount documentation <https://as-types.docs.massa.net/classes/Amount.html>`_.
```

2023-01-17 16:59 UTC, gregLibert commented on web3-dev/types.rst
> +A class used to serialize and deserialize function argument.
```suggestion
A class used to serialize and deserialize arguments (of functions, data to/from storage...).
```

2023-01-17 16:59 UTC, gregLibert commented on web3-dev/types.rst
> +See all Args methods and supported types for serialization at `Args documentation <https://as-types.docs.massa.net/classes/Args.html>`_.
```suggestion
See all Args methods and supported types for serialization/deserialization in the `Args documentation <https://as-types.docs.massa.net/classes/Args.html>`_.
```

2023-01-18 08:37 UTC, Thykof approved these changes

2023-01-18 09:13 UTC, gregLibert approved these changes
:+1:

2023-01-18 17:24 UTC, merged